### ISSUE TITLE
Remove Chrome Frame HTTP header hint

### ISSUE THREAD

**Issue by alrra** [h5bp/server-configs-iis#1]
Google officially announced that they've decided to retire Chrome Frame: http://blog.chromium.org/2013/06/retiring-chrome-frame.html.

---

@ChrisMcKee maybe postponed removing the Chrome Frame HTTP header hint until after IIS gets to a more stable release, v1.0.0 ?

**Comment by Jogai** [comment]
This hint is still set in https://github.com/h5bp/server-configs-iis/blob/master/server%20config/Web.config#L203

**Comment by ChrisMcKee** [comment]
@Jogai yep, its harmless and allows things still using it to continue working.
