### ISSUE TITLE
chrome=1 can be removed

### ISSUE THREAD

**Issue by coliff** [h5bp/server-configs-iis#21]
chrome=1 can be removed in the snippet:
<add name="X-UA-Compatible" value="IE=Edge,chrome=1"/>

Google's ChromeFrame has been discontinued and is no longer available.

**Comment by ChrisMcKee** [comment]
Hi,
  I'll have to check what the rest of the boilerplates are doing as the original convo was a while back https://github.com/h5bp/server-configs-iis/issues/1
