### ISSUE TITLE
remove chrome=1

### ISSUE THREAD

**Issue by urrgur** [h5bp/server-configs-iis#23]
removed from all other configs as well. No reason for it to be there still.

**Comment by arthurvr** [comment]
That's correct indeed. We removed it from all other server configs years ago. @ChrisMcKee why did you close https://github.com/h5bp/server-configs-iis/issues/21? No reason to keep it in right?

**Comment by ChrisMcKee** [comment]
@arthurvr because the removal 'at the time' was contentious https://github.com/h5bp/server-configs-iis/issues/1 yeah It can go now.

**Comment by ChrisMcKee** [comment]
Will be dealt with along side https://github.com/h5bp/server-configs-iis/issues/25#issuecomment-107381452

**Comment by arthurvr** [comment]
@ChrisMcKee Why do you lock this conversation? **open**-source means having people involved with the conversations and decisions in your project, no? Just wondering, you might have a perfect reason ;)

**Comment by ChrisMcKee** [comment]
@arthurvr any further queries should be added to #25 for now; the rest will be closed when I push up the reduced config. Feel free to ask me the random stuff on twitter, I've little time for chat in issues.
