### ISSUE TITLE
Wrong and duplicate ETag removal

### ISSUE THREAD

**Issue by gdoron** [h5bp/server-configs-iis#27]
Removing the ETag header is written twice in the web.config.
The first one is with custom HTTP header:

<remove name="ETAG" /><add name="ETAG" value="" />
And the second one is with URL rewrite.

Besides from being duplicate, the first option doesn't actually work:
http://stackoverflow.com/a/1250987/601179
(And I verified it today)

BTW, for IIS 8 there is a new way:
http://stackoverflow.com/a/26789473/601179

**Comment by ChrisMcKee** [comment]
Ta

**Comment by gdoron** [comment]
Do you need a pull request for this?
It should be pretty no brainier to fix.

**Comment by ChrisMcKee** [comment]
Ha! no I was foot tapping waiting to do a much larger release.
