### ISSUE TITLE
Keep-Alive

### ISSUE THREAD

**Issue by AaronLayton** [h5bp/server-configs-iis#29]
Should these have the `Keep-Alive` attribute?

```
<httpProtocol allowKeepAlive="true">
```

**Comment by ChrisMcKee** [comment]
Technically no, standard 'wanted' behaviour for most sites is true; and true is default :)

```
Specifies whether keep-alive processing is permitted (true) or not (false).

The default value is true.
```
https://www.iis.net/configreference/system.webserver/httpprotocol

**Comment by AaronLayton** [comment]
Ah so only need to specify the `true` if its been turned off by the server admins?

**Comment by ChrisMcKee** [comment]
@AaronLayton yeah you can change the defaults at server level in IIS manager; it would be odd to disable it by default but there's always some well meaning fool :)
As above I'll probably add it in with some notes.
Out of interest what version of IIS are you using (trying to gauge use).

**Comment by AaronLayton** [comment]
using IIS 7.5 ;-)

**Comment by ChrisMcKee** [comment]
Ta :+1:
