### ISSUE TITLE
Adding package.json

### ISSUE THREAD

**Issue by teodragovic** [h5bp/server-configs-iis#35]
It would be great to have possibility of including this repo via npm - [use case](https://github.com/google/web-starter-kit/blob/master/gulpfile.babel.js#L64)

**Comment by ChrisMcKee** [comment]
@teodragovic I've nothing against this; but npm already allows you to install from a github repo, I suppose I'd just need to add a package.json file to make it work. 
Then it would be up to the user to set gulp to transfer the appropriate file web.config to a location of their choosing (or webpack etal)
