### ISSUE TITLE
IIS 8 - remove ETAG comment

### ISSUE THREAD

**Issue by K-Thompson** [h5bp/server-configs-iis#37]
First, thank you for this project. Very helpful.

Not to pick nits, but I suspect this comment isn't quite correct:

> &lt;staticContent&gt;
> 	&lt;!-- Remove **ETAG IN IIS &gt;8** ; for IIS 7/7.5 see the Rewrite rules (bigger description of why you might remove etag down there aswell)
> 	&lt;clientCache setEtag="false"/&gt;
> 	--&gt;

Should probably read:   ETAG IN IIS &gt;=8

**Comment by ChrisMcKee** [comment]
Yep you're correct.
